name: TerminatorNPC
version: ${project.version}
main: me.swipez.terminatornpc.TerminatorNPC
api-version: 1.18
authors: [ notnotnotswipez, Daxanius ]
depend: [Citizens]
commands:
  terminator:
    usage: /terminator <playername> <number of bots>
  clearterminators:
    usage: /clearterminators
  terminatorloadout:
    usage: /terminatorloadout
  terminatorignore:
    usage: /terminatorignore <playername>